## Forwardprop and Backprop implementation

In [3]:
import numpy as np

#### initialing input and target labels

In [13]:
x= np.random.randint(0, high=2, size=(3,4), dtype= int) #input values shaped 3x4
y = np.random.randint(0, high=2, size=(3,1), dtype= int) #target label 3x1
print('input array:\n',x, '\n label:\n',y)

input array:
 [[0 1 0 1]
 [0 1 1 0]
 [1 1 0 0]] 
 label:
 [[0]
 [1]
 [1]]


###### Network consist of 1 input layer, 1 hidden layer, 1 prediction layer

### initialing weights and biases

In [5]:
w1 =np.random.rand(4,3)
b1 =np.random.rand(1,3)
print('weights for layer 1: \n',w1,'\n \n biases for layer 1: ',b1)
w2 =np.random.rand(3,1)
b2 =np.random.rand(1,1)
print('\n \n weights for layer 2: \n',w2,'\n \n biases for layer 2:',b2)


weights for layer 1: 
 [[0.88184325 0.08059041 0.77275236]
 [0.54627936 0.39956654 0.49316124]
 [0.20881688 0.19818137 0.17340361]
 [0.22690923 0.22487492 0.50761497]] 
 
 biases for layer 1:  [[0.85583134 0.51538744 0.38619048]]

 
 weights for layer 2: 
 [[0.3194988 ]
 [0.04253225]
 [0.22386386]] 
 
 biases for layer 2: [[0.45871629]]


### Forward prop

###### Sigmoid activation function

In [6]:
def sigmoid(arg):
    return 1/(1+ np.exp(-arg))

In [7]:
print('input array x shaped:{_}, w1 shaped:{w} and b1 is shaped:{b}'.format(_=x.shape, w=w1.shape, b= b1.shape))

input array x shaped:(3, 4), w1 shaped:(4, 3) and b1 is shaped:(1, 3)


#### computing activations for hidden layer
* activations are shaped 3x4

In [8]:
act1 = sigmoid(np.dot(x,w1) +b1)#sigmoid activations for first layer
print(act1)

[[0.83603533 0.75764822 0.80010755]
 [0.87702817 0.69441733 0.84111635]
 [0.74357782 0.67118926 0.63635862]]


In [9]:
print('hidden layer input act1 shaped:{_}, w2 shaped:{w} and b2 is shaped:{b}'.format(_=act1.shape, w=w2.shape, b= b2.shape))

hidden layer input act1 shaped:(3, 3), w2 shaped:(3, 1) and b2 is shaped:(1, 1)


#### computing activations for prediction layer
* activations are shaped 3x1

In [10]:
act2 = sigmoid(np.dot(act1,w2) +b2) #sigmoid activation for prediction layer
print(act2)

[[0.7185273 ]
 [0.72247192]
 [0.7041822 ]]


### Backprop
* computing slope for final layer activations
* computing error at final layer as (y- act2)*slope_finalactivation

In [11]:
#error at outmost layer = actual label - predicted label, i.e. y- act2
#e3 = y- act2
dact2 = act2*(1-act2) #slope for final layer activations
e2 = (y- act2)*dact2 #error at final layer


#e2 = np.dot(w2.T,e3)*dact2 #at second layer
dact1 = act1*(1-act1)##slope for hidden layer activations
e1 = np.dot(e2, w2.T)*dact1  #error at hidden layer


print('errors for final layer:\n', e2, '\n errors for hidden layer: \n', e1)

errors for final layer:
 [[ 0.05692668]
 [ 0.05564611]
 [-0.14668793]] 
 errors for hidden layer: 
 [[ 0.00249322  0.00044458  0.00203819]
 [ 0.00191745  0.00050223  0.00166477]
 [-0.00893605 -0.0013769  -0.00759895]]


#### Updating Weights and Biases

In [12]:
w2 =w2 + np.dot(act1.T,e2)*0.1 # 0.1 is the learning rate
w1= w1 + np.dot(x.T,e1)*0.1 # 0.1 is the learning rate

b2 = b2 +np.sum(e2, axis=0)*0.1
b1 = b1 +np.sum(e1, axis=0)*0.1

print("\n updated w2:\n",w2, "\n updated w1:\n",w1, "\n updated b2:\n",b2, "\n updated b1:\n",b1)


 updated w2:
 [[0.318231  ]
 [0.04086391]
 [0.22376448]] 
 updated w1:
 [[0.882035   0.08064064 0.77291884]
 [0.54652868 0.399611   0.49336506]
 [0.20792327 0.19804368 0.17264371]
 [0.22735029 0.2249696  0.50798526]] 
 updated b2:
 [[0.45530478]] 
 updated b1:
 [[0.8553788  0.51534443 0.38580088]]
